#javascript_compressor: closure
gzip_assets: on

javascripts:
  common:
    - public/javascripts/libs/jquery.min.js    
    - public/javascripts/libs/jquery_ujs.js   
    - public/javascripts/libs/jquery.mobile.js   
    - public/javascripts/*.js   
  test:
    - public/javascripts/libs/qunit-git.js
    - public/javascripts/test/wdcv-test.js
    
stylesheets:
  common:    
    - public/stylesheets/libs/jquery.mobile.css    
    - public/stylesheets/assorted.css
    - public/stylesheets/pages/*.css
  test:
    - public/stylesheets/libs/qunit-git.css